### ISSUE TITLE
下一步的功能扩展里面有没有发送link和小程序的功能，期待！！

### ISSUE THREAD

**Issue by wolfgangsk07** [UoUoio/WechatBot#1]
如题，感谢大佬的贡献

**Comment by UoUoio** [comment]
我一直以为我回复过了...  很抱歉
这个项目仅仅是作为一个连接的客户端, 注入相关要看这个项目是不是增加了扩展接口
也就是这个项目是依赖于
https://github.com/cixingguangming55555/wechat-bot
