### ISSUE TITLE
项目启动不了

### ISSUE THREAD

**Issue by rusher666** [UoUoio/WechatBot#3]
22:49:14.620 [main] INFO  i.u.w.WechatBotApplication - [logStarting,55] - Starting WechatBotApplication using Java 1.8.0_131 on T440p-4710MQ with PID 16412 (D:\SuperCloudWorkSpace\WechatBot\target\classes started by Administrator in D:\SuperCloudWorkSpace\WechatBot)
22:49:14.623 [main] DEBUG i.u.w.WechatBotApplication - [logStarting,56] - Running with Spring Boot v2.4.3, Spring v5.3.4
22:49:14.624 [main] INFO  i.u.w.WechatBotApplication - [logStartupProfileInfo,664] - The following profiles are active: default
22:49:15.405 [main] INFO  o.a.c.h.Http11NioProtocol - [log,173] - Initializing ProtocolHandler ["http-nio-8080"]
22:49:15.406 [main] INFO  o.a.c.c.StandardService - [log,173] - Starting service [Tomcat]
22:49:15.406 [main] INFO  o.a.c.c.StandardEngine - [log,173] - Starting Servlet engine: [Apache Tomcat/9.0.43]
22:49:15.479 [main] INFO  o.a.c.c.C.[.[.[/] - [log,173] - Initializing Spring embedded WebApplicationContext
22:49:15.790 [main] INFO  o.a.c.h.Http11NioProtocol - [log,173] - Starting ProtocolHandler ["http-nio-8080"]
22:49:15.819 [main] INFO  i.u.w.WechatBotApplication - [logStarted,61] - Started WechatBotApplication in 1.766 seconds (JVM running for 3.193)
通信连接出现异常:Connection refused: connect
已断开连接... 
请问如何解决

**Comment by rusher666** [comment]
通过个人微信发送消息不需要token或私钥吗？请解答

**Comment by UoUoio** [comment]
> 22:49:14.620 [main] INFO iuwWechatBotApplication - [logStarting,55] - 在 PID 16412 的 T440p-4710MQ 上使用 Java 1.8.0_131 启动 WechatBotApplication（D:\SuperCloudWorkSpace\WechatBot\target\classes 由管理员在 D:\SuperCloudWorkSpace 中启动\WechatBot) 22:49:14.623 [main] DEBUG iuwWechatBotApplication - [logStarting,56] - 使用 Spring Boot v2.4.3、Spring v5.3.4 运行 22:49:14.624 [main] INFO iuwWechatBotApplication - [logStartupProfileInfo,664] - The以下配置文件处于活动状态：默认 22:49:15.405 [main] INFO oachHttp11NioProtocol - [log,173] - Initializing ProtocolHandler ["http-nio-8080"] 22:49:15.406 [main] INFO oaccStandardService - [log,173] - 启动服务 [Tomcat] 22:49:15.406 [main] INFO oaccStandardEngine - [log,173] - 启动 Servlet 引擎：[Apache Tomcat/9.0.43] 22:49:15.479 [main] INFO oaccC[.[.[/] - [log, 173] - 初始化 Spring 嵌入式 WebApplicationContext 22:49:15.790 [main] INFO oachHttp11NioProtocol - [log,173] - 启动 ProtocolHandler ["http-nio-8080"] 22:49:15.819 [main] INFO iuwWechatBotApplication - [logStarted,61 Started WeBotBotApplication in 1.6 seconds (JVM running for 3.193) 通信连接异常Connection denied: connect 已终止连接7... 请问如何解决

請先確保你已經對wechat進行注入

**Comment by UoUoio** [comment]
> 通过个人微信发送消息，不需要匿名或私信吗？请回答

我不是很明白你的意思，你說的匿名或者私信是指的什麼？....

**Comment by UoUoio** [comment]
> 通过个人微信发送消息不需要token或私钥吗？请解答

不需要的，這只是一個本地啓動的小項目，如果你打算將它部署到服務器建議添加上一些Token驗證

**Comment by rusher666** [comment]
>
