### ISSUE TITLE
如何调用内部接口直接获取nickname

### ISSUE THREAD

**Issue by ha1c9on** [UoUoio/WechatBot#6]
目前sb的方案中采用了post `getnicknae`的方式在console获取nickname 如何调用内部接口而非http访问直接获取nickname的相关json

发现直接new wechatbot 调用`GetNickname`返回空指针

**Comment by UoUoio** [comment]
如果没记错的话这个注入的dll不支持获取吧
可以看下这个:是全部的支持的功能https://github.com/cixingguangming55555/wechat-bot/blob/master/client/httpclient.js

**Comment by UoUoio** [comment]
> 目前sb的方案中采用了post `getnicknae`的方式在console获取nickname 如何调用内部接口而非http访问直接获取nickname的相关json
> 
> 发现直接new wechatbot 调用`GetNickname`返回空指针
你说的通过5555端口直连dll获取的方式,如果没记错这个dll不支持你说的这种获取,具体可以看下这个本身支持的功能.
https://github.com/cixingguangming55555/wechat-bot/blob/master/client/httpclient.js

**Comment by UoUoio** [comment]
> 目前sb的方案中采用了post `getnicknae`的方式在console获取nickname 如何调用内部接口而非http访问直接获取nickname的相关json
> 
> 发现直接new wechatbot 调用`GetNickname`返回空指针

你说的通过5555端口直连dll获取的方式,如果没记错这个dll不支持你说的这种获取,具体可以看下这个本身支持的功能.
https://github.com/cixingguangming55555/wechat-bot/blob/master/client/httpclient.js

**Comment by ha1c9on** [comment]
看源码也是用ws建立了一个长连接去推送ws消息，不知道为什么复用不可以

**Comment by UoUoio** [comment]
> 看源码也是用ws建立了一个长连接去推送ws消息，不知道为什么复用不可以

是嘞

**Comment by UoUoio** [comment]
> 看源码也是用ws建立了一个长连接去推送ws消息，不知道为什么复用不可以

你说的复用不可以是指的什么呢?

**Comment by ha1c9on** [comment]
您好 已经解决问题了 感谢

**Comment by UoUoio** [comment]
怎么解决的么  能分享下么   后边来人遇到同样问题了  也可以借鉴一下

**Comment by ha1c9on** [comment]
> 怎么解决的么 能分享下么 后边来人遇到同样问题了 也可以借鉴一下

我把您的代码直接重构掉了 不采用http了 直接内部处理了

**Comment by UoUoio** [comment]
> > 怎么解决的么 能分享下么 后边来人遇到同样问题了 也可以借鉴一下
> 
> 我把您的代码直接重构掉了 不采用http了 直接内部处理了

可以可以, 我竟还不知什么时候增加了获取nickname的功能
