### ISSUE TITLE
wechatCommon 接口中的type字段枚举值具体有哪些呢？

### ISSUE THREAD

**Issue by pick7** [UoUoio/WechatBot#7]
这个wechatCommon 接口中的type字段枚举值具体有哪些呢？

`{
	"wxid": "wxid_ludi6ta3te4h12",
	"roomid": "22656912702@chatroom",
	"type": "5020",
	"content": "xxx"
}`

**Comment by UoUoio** [comment]
https://github.com/UoUoio/WechatBot/blob/main/src/main/java/io/uouo/wechatbot/common/WechatBotCommon.java
看下这个
