### ISSUE TITLE
需要注入到微信中的dll在哪里可以找到?

### ISSUE THREAD

**Issue by lumeijin** [UoUoio/WechatBot#8]
提到的那个项目好像已经被清空了,请问作者有dll的备份吗

**Comment by ghostxu97** [comment]
蹲一个dll

**Comment by UoUoio** [comment]
> 提到的那个项目好像已经被清空了,请问作者有dll的备份吗

已经更新 @lumeijin @ghostxu97 
https://github.com/UoUoio/WechatBot/releases/download/4.7.5.66/wechat-bot-.zip
